// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrpxyvijulbpdyjvfxmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycHh5dmlqdWxicGR5anZmeG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDcyNDcsImV4cCI6MjA2NjQyMzI0N30.QVrAPbSvE6Kl9dtHQPzPcH20F0psrFb_tmm6sko4tcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);